// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Models;

namespace Movies.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220202185418_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Movies.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Romantic Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Comic Action"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Western"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Romance"
                        });
                });

            modelBuilder.Entity("Movies.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "The Dark Knight",
                            Notes = "Cool Batman Movie",
                            Rating = "PG-13",
                            Year = 2012
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 2,
                            Director = "Donald Petrie",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "How to Lose a Guy in 10 Days",
                            Notes = "Funny movie about love",
                            Rating = "PG-13",
                            Year = 2003
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 3,
                            Director = "The Russo Brothers",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "Avengers: Infinity War",
                            Notes = "Crazy",
                            Rating = "PG-13",
                            Year = 2018
                        });
                });

            modelBuilder.Entity("Movies.Models.MovieResponse", b =>
                {
                    b.HasOne("Movies.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
